# Generated by Django 3.2.7 on 2021-10-23 18:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_project_pre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.CharField(max_length=20, verbose_name='Nro documento')),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('date_venc', models.DateField(default=datetime.datetime.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('igv', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.client')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetIngreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cant', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.ingreso')),
                ('proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.project')),
            ],
            options={
                'verbose_name': 'Detalle de Ingreso',
                'verbose_name_plural': 'Detalle de Ingresos',
                'ordering': ['id'],
            },
        ),
    ]
