# Generated by Django 3.2.7 on 2021-10-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project/%Y/%m/%d', verbose_name='Imagen'),
        ),
    ]
